IQMStarterKit/Models/GroupTutorModel.cs
using System;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace IQMStarterKit.Models
{
    public class GroupTutorModel
    {
        [Key, DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public byte GroupTutorId { get; set; }

        [Required]
        public byte GroupId { get; set; }

        [Required]
        public string TutorId { get; set; }

        [Required]
        public string TutorName { get; set; }

        //system fields
        [Required]
        public DateTime CreatedDateTime { get; set; }

        [Required]
        [StringLength(100)]
        public string CreatedBy { get; set; }

        [Required]
        public DateTime ModifiedDateTime { get; set; }

        [Required]
        [StringLength(100)]
        public string ModifiedBy { get; set; }

        [DefaultValue(0)]
        public bool IsRemoved { get; set; }




    }
}

IQMStarterKit/Models/GroupTutorModelView.cs
using System.Collections.Generic;

namespace IQMStarterKit.Models
{
    public class GroupTutorModelView
    {
        public GroupModel GroupModel { get; set; }
        public IEnumerable<GroupTutorModel> GroupTutorModel { get; set; }
        public IEnumerable<ApplicationUser> Tutors { get; set; }
    }
}

IQMStarterKit/Controllers/GroupTutorModelsController.cs
using IQMStarterKit.Models;
using IQMStarterKit.Models.Alert;
using System;
using System.Linq;
using System.Net;
using System.Web.Mvc;

namespace IQMStarterKit.Controllers
{
    public class GroupTutorModelsController : CommonController
    {
        private ApplicationDbContext _context = new ApplicationDbContext();

        // GET: GroupTutorModels
        public ActionResult Index(byte Id)
        {
            var model = new GroupTutorModelView();
            //get group info
            model.GroupModel = _context.GroupModels.FirstOrDefault(m => m.GroupId == Id);
            model.GroupTutorModel = _context.GroupTutorModels.Where(m => m.GroupId == Id).ToList();
            model.Tutors = GetTutors(Id);

            return View(model);
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult AddTutor(GroupTutorModelView groupTutorView)
        {
            var groupTutor = new GroupTutorModel();
            string newTutor = Convert.ToString(Request.Form["AddTutor"]);

            if (newTutor == null) return RedirectToAction("Index", new { Id = groupTutorView.GroupModel.GroupId }).WithWarning("No tutor to add");

            try
            {
                groupTutor.CreatedBy = GetSessionUserId();
                groupTutor.CreatedDateTime = DateTime.Now;
                groupTutor.ModifiedBy = GetSessionUserId();
                groupTutor.ModifiedDateTime = DateTime.Now;

                groupTutor.GroupId = groupTutorView.GroupModel.GroupId;
                groupTutor.TutorId = newTutor;
                groupTutor.TutorName = GetFullName(newTutor);

                //save tutor
                _context.GroupTutorModels.Add(groupTutor);
                _context.SaveChanges();



                return RedirectToAction("Index", new { Id = groupTutorView.GroupModel.GroupId }).WithSuccess("Tutor added successfully!");

            }
            catch (Exception ex)
            {

                return View(groupTutorView).WithError("Insert Error: " + ex.Message);
            }




        }


        // Utility


        public ActionResult Delete(int id, string groupId)
        {
            if (id == 0)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            GroupTutorModel groupModelTutor = _context.GroupTutorModels.Where(m => m.GroupTutorId == id).FirstOrDefault();
            if (groupModelTutor == null)
            {
                return HttpNotFound();
            }
            _context.GroupTutorModels.Remove(groupModelTutor);
            _context.SaveChanges();

            return RedirectToAction("Index", new { Id = groupId }).WithSuccess("Deleted successfully!");
        }


    }
}

IQMStarterKit/Views/GroupTutorModels/Index.cshtml
@model IQMStarterKit.Models.GroupTutorModelView

<h2>Group [@Model.GroupModel.GroupName]</h2>

@using (Html.BeginForm("AddTutor", "GroupTutorModels", FormMethod.Post))
{
    @Html.AntiForgeryToken()
    <br />
    @Html.HiddenFor(model => model.GroupModel.GroupId)
    @Html.ValidationSummary(true,
        "",
        new { @class = "text-danger" })
    <div class="col-md-5 form-inline" style="margin-bottom:20px;">
        @Html.ActionLink("Back",
            "Index", "GroupModels",
            null,
            new { @class = "btn btn-default" })
        <input type="submit" value="Add Tutor" class="btn btn-default" />
       @Html.DropDownList("AddTutor", new SelectList(Model.Tutors, "Id", "FullName"), new { @class = "form-control" })
    </div>

    <br />

    <table id="group" class="display;" style="width:60%;">
        <thead>
            <tr>
                <th>
                    Assigned Tutor:
                </th>
                <th></th>
            </tr>
        </thead>
        <tbody>

            @foreach (var item in Model.GroupTutorModel)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.TutorName)
                    </td>
                    <td>
                         @Html.ActionLink("Delete", "Delete",
                            new { Id = item.GroupTutorId, groupId = Model.GroupModel.GroupId },
                            new
                            {
                                onclick =
                                    "return confirm('Are you sure you wish to remove this tutor from the group?');"
                            })
                        
                    </td>
                </tr>
            }
        </tbody>
    </table>

    

}


@section Scripts {

    <script>
        $(document).ready(function () {
            $('#group').DataTable({
                "bLengthChange": false,
                "bFilter": false,
                "paging": false

            });



        });

    </script>

}