IQMStarterKit/Models/Core/GroupActivityConfig.cs
using System;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace IQMStarterKit.Models.Core
{
    public class GroupActivityConfig
    {
        [Key, DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public byte GroupActivityConfigId { get; set; }

        [Required]
        public byte GroupId { get; set; }

        [Required]
        public byte TempActivityId { get; set; }

        [DefaultValue(0)]
        public bool IsLocked { get; set; }

        [StringLength(1000)]
        public string Remarks { get; set; }


        //system fields
        [Required]
        public DateTime CreatedDateTime { get; set; }

        [Required]
        [StringLength(100)]
        public string CreatedBy { get; set; }

        [Required]
        public DateTime ModifiedDateTime { get; set; }

        [Required]
        [StringLength(100)]
        public string ModifiedBy { get; set; }




    }
}

IQMStarterKit/Controllers/GroupActivityConfigsController.cs
using IQMStarterKit.Models;
using IQMStarterKit.Models.Alert;
using IQMStarterKit.Models.Core;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Web.Mvc;

namespace IQMStarterKit.Controllers
{
    [Authorize(Roles = "Administrator,Tutor")]
    public class GroupActivityConfigsController : CommonController
    {
        private ApplicationDbContext _context = new ApplicationDbContext();

        // GET: GroupActivityConfigs
        public ActionResult Index(string GroupId)
        {
            var configModel = new ConfigViewModel();
            var groupId = byte.Parse(GroupId);
            var tempConfigs = new List<TempActivityConfig>();
            // load target group to configure
            configModel.GroupModel = _context.GroupModels
                .Where(m => m.GroupId == groupId)
                .FirstOrDefault();
            // load temp activities
            var tempActivities = _context.TempActivities
                .Where(m => m.IsRemoved == false)
                .OrderBy(m => m.SortOrder).ToList();

            var groupConfig = _context.GroupActivityConfig
                .Where(m => m.GroupId == groupId).ToList();


            foreach (var item in tempActivities)
            {
                var newActivityConfig = new TempActivityConfig();
                //newActivityConfig
                newActivityConfig.TempActivityId = item.TempActivityId;
                newActivityConfig.TempModuleId = item.TempModuleId;
                newActivityConfig.Title = item.Title;
                newActivityConfig.Description = item.Description;
                newActivityConfig.SortOrder = item.SortOrder;

                var _config = groupConfig
                    .Where(m => m.GroupId == groupId && m.TempActivityId == item.TempActivityId)
                    .FirstOrDefault();

                if (_config != null)
                {
                    newActivityConfig.GroupActivityConfigId = _config.GroupActivityConfigId;
                    newActivityConfig.GroupId = _config.GroupId;
                    newActivityConfig.IsLocked = _config.IsLocked;
                    newActivityConfig.Remarks = _config.Remarks;
                    newActivityConfig.CreatedBy = GetFullName(_config.CreatedBy);
                    newActivityConfig.CreatedDateTime = _config.CreatedDateTime;
                    newActivityConfig.ModifiedBy = GetFullName(_config.ModifiedBy);
                    newActivityConfig.ModifiedDateTime = _config.ModifiedDateTime;

                }

                tempConfigs.Add(newActivityConfig);

            }


            configModel.TempActivitiesConfig = tempConfigs.OrderBy(m => m.SortOrder).ToList();


            return View(configModel);
        }

        // UPDATE
        [HttpPost]
        public ActionResult SaveConfig(FormCollection fc)
        {
            var tempConfigs = new List<TempActivityConfig>();
            var groupId = Request.Form["GroupId"];
            var byteGroupId = byte.Parse(groupId);
            bool updateFlag = false;


            // load temp activities
            var tempActivities = _context.TempActivities.Where(m => m.IsRemoved == false).ToList();

            var groupConfig = _context.GroupActivityConfig.Where(m => m.GroupId == byteGroupId).ToList();


            foreach (var item in tempActivities)
            {
                var newActivityConfig = new TempActivityConfig();
                bool locker = false;

                newActivityConfig.GroupId = byteGroupId;
                newActivityConfig.TempActivityId = item.TempActivityId;
                newActivityConfig.TempModuleId = item.TempModuleId;
                newActivityConfig.Title = item.Title;
                newActivityConfig.Description = item.Description;
                newActivityConfig.SortOrder = item.SortOrder;

                var _config = groupConfig.Where(m => m.TempActivityId == item.TempActivityId).FirstOrDefault();

                var new_lock = Request.Form["lock" + item.TempActivityId];
                var new_remark = Request.Form["remark" + item.TempActivityId];


                if (new_lock != "false") locker = true;

                newActivityConfig.IsLocked = locker;
                newActivityConfig.Remarks = new_remark.Trim();

                if (_config != null)
                {
                    updateFlag = true;
                    newActivityConfig.GroupActivityConfigId = _config.GroupActivityConfigId;
                    newActivityConfig.GroupId = _config.GroupId;
                    newActivityConfig.IsLocked = (locker != _config.IsLocked) ? locker : _config.IsLocked;
                    newActivityConfig.Remarks = new_remark.Trim();
                    newActivityConfig.CreatedBy = _config.CreatedBy;
                    newActivityConfig.CreatedDateTime = _config.CreatedDateTime;
                    newActivityConfig.ModifiedBy = _config.ModifiedBy;
                    newActivityConfig.ModifiedDateTime = _config.ModifiedDateTime;


                }

                tempConfigs.Add(newActivityConfig);

            }


            foreach (var item in tempConfigs)
            {


                var model = _context.GroupActivityConfig.Where(m => m.GroupActivityConfigId == item.GroupActivityConfigId).FirstOrDefault();

                if (model != null)
                {
                    model.IsLocked = item.IsLocked;
                    model.Remarks = item.Remarks;
                    model.ModifiedBy = GetSessionUserId();
                    model.ModifiedDateTime = DateTime.Now;
                }
                else
                {
                    model = new GroupActivityConfig();

                    model.GroupId = item.GroupId;
                    model.TempActivityId = item.TempActivityId;
                    model.IsLocked = item.IsLocked;
                    model.Remarks = item.Remarks;

                    model.CreatedBy = (updateFlag) ? item.CreatedBy : GetSessionUserId();
                    model.CreatedDateTime = (updateFlag) ? item.CreatedDateTime : DateTime.Now;
                    model.ModifiedBy = GetSessionUserId();
                    model.ModifiedDateTime = DateTime.Now;
                }

                try
                {
                    if (updateFlag)
                    {
                        _context.Entry(model).State = EntityState.Modified;
                    }
                    else
                    {
                        _context.GroupActivityConfig.Add(model);
                    }

                    _context.SaveChanges();

                }
                catch (Exception ex)
                {

                    return RedirectToAction("Index", new { @GroupId = groupId }).WithError(ex.Message);
                }



            }

            return RedirectToAction("Index", new { @GroupId = groupId }).WithSuccess("Saved successfully!");
        }


    }
}

IQMStarterKit/Views/GroupActivityConfigs/Index.cshtml
@model IQMStarterKit.Models.ConfigViewModel

<h3>Configuration for Group: @Model.GroupModel.GroupName</h3>

@using (Html.BeginForm("SaveConfig", "GroupActivityConfigs", FormMethod.Post))
{

    @Html.Hidden("GroupId", Model.GroupModel.GroupId.ToString())
    
    

    <table style="width:100%" class="table table-striped table-bordered" id="config" cellspacing="0">
        <thead>
            <tr>
                <th>Module</th>
                <th>Activity Title</th>
                <th>Description</th>
                <th>IsLocked</th>
                <th>Remarks</th>
                <th>Created By</th>
                <th>Modified By</th>
            </tr>
        </thead>
        <tbody>
           
           

            @foreach (var item in Model.TempActivitiesConfig.OrderBy(m=>m.SortOrder))
            {

                var idname = "remark" + item.TempActivityId;

                <tr>
                    <td>Module @Html.DisplayFor(modelmItem => item.TempModuleId)</td>
                    <td>@Html.DisplayFor(modelItem => item.Title)</td>
                    <td>@Html.DisplayFor(modelItem => item.Description)</td>
                    <td align="center">@Html.CheckBox("lock" + item.TempActivityId, item.IsLocked)</td>
                    <td><input type="text" id="@idname" name="@idname" class = "form-control" value="@item.Remarks" /></td>
                    <td>
                        <h6>
                            @Html.DisplayFor(modelItem => item.CreatedBy)<br/>
                            <small>[
                                @if (item.CreatedDateTime.ToString() != "1/1/0001 12:00:00 AM")
                                { @Html.DisplayFor(modelItem => item.CreatedDateTime);
                                }]
                            </small>
                        </h6>
                    </td>
                    <td>
                        <h6>
                            @Html.DisplayFor(modelItem => item.ModifiedBy)<br />
                            <small>
                                [
                                @if (item.ModifiedDateTime.ToString() != "1/1/0001 12:00:00 AM")
                                { @Html.DisplayFor(modelItem => item.ModifiedDateTime);
                                }]
                            </small>
                        </h6>
                    </td>
                   
                   
                </tr>
            }
        </tbody>
    </table>
    <br/>
    <input type="submit" value="Save Configuration" class="btn btn-primary"/>
    <input id="checkall" type="button" class="btn btn-default" value="Check All" />
    @Html.ActionLink("Back to List", "Index", "GroupModels", null, new { @class = "btn btn-default"})

}

    @section scripts{
        <script>
        $(document).ready(function () {
            $('#config').DataTable({
                "bLengthChange": false,
                "bFilter": false,
                "paging": false,
                "sorting": false
            });

            $('#checkall').click(function () {
                //alert($(this).val());
                if ($(this).val() == "Check All") {
                    $('input:checkbox').attr('checked', 'checked');
                    $(this).val('Uncheck All')
                } else {
                    $('input:checkbox').removeAttr('checked');
                    $(this).val('Check All');
                }
});
        });

          
        </script>
    }